### ISSUE TITLE
Buscar mais modelos 

### ISSUE THREAD

**Issue by nahumsa** [coviseg/Baselines#3]
Além da ResNet, seria bom aplicar mais modelos para termos um benchmark mais preciso.

- [x] MAML

**Comment by cdebom** [comment]
Jax MAML: https://jax.readthedocs.io/en/stable/notebooks/maml.html

Objetivo: rodar nos dados de covid com 5, 10 shot e obter o predict e a ROC no restante dos dados.

**Comment by nahumsa** [comment]
> Jax MAML: https://jax.readthedocs.io/en/stable/notebooks/maml.html
> 
> Objetivo: rodar nos dados de covid com 5, 10 shot e obter o predict e a ROC no restante dos dados.

Implementei o MAML nesse [notebook](https://github.com/coviseg/Baselines/blob/master/MAML%20Covid.ipynb).
